import type { Metadata } from 'next'
import './globals.css'
import NavBar from '@/ui/NavBar'
import React from 'react'
import { ProductProvider } from '@/context/PorductContext'
import { getProductData } from '@/services/getComponentsFromStrapi'

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default async function RootLayout ({
  children,
}: {
  children: React.ReactNode
}) {
  const products = await getProductData()

  return (
    <html lang='en'>
      <ProductProvider products={products}>
        <body>
          <NavBar />
          {children}
        </body>
      </ProductProvider>
    </html>
  )
}
