import type { Metadata } from 'next'
import './globals.css'
import NavBar from '@/ui/NavBar'
import React from 'react'
import { ProductProvider } from '@/context/PorductContext'

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout ({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang='en'>
      <ProductProvider>
        <body>
          <NavBar />
          {children}
        </body>
      </ProductProvider>
    </html>
  )
}
